export const trafficSigns = [
	{ name: "Финиш", texture: "win.jpg", function: "win" },
	{ name: "Движение без остановки запрещено", texture: "001.jpg", function: "stopped" },
	{ name: "Въезд запрещён", texture: "002.jpg" },
	{ name: "Движение грузовых автомобилей запрещено", texture: "003.jpg", function: "vehicleType != 'truck'" },
	{ name: "Движение грузовиков с опасным грузом запрещено", texture: "004.jpg", function: "vehicleType != 'hazmat'" },
	{ name: "Движение грузовиков запрещено", texture: "005.jpg", function: "vehicleType != 'truck'" },
	{ name: "Движение тракторов запрещено", texture: "006.jpg", function: "vehicleType != 'tractor'" },
	{ name: "Движение мотоциклов запрещено", texture: "007.jpg", function: "vehicleType != 'motorcycle'" },
	{ name: "Движение мопедов запрещено", texture: "008.jpg", function: "vehicleType != 'moped'" },
	{ name: "Движение велосипедов запрещено", texture: "009.jpg", function: "vehicleType != 'bicycle'" },
	{ name: "Движение пешеходов запрещено", texture: "010.jpg", function: "vehicleType != 'pedestrian'" },
	{ name: "Движение тележек запрещено", texture: "011.jpg", function: "vehicleType != 'cart'" },
	{ name: "Движение гужевого транспорта запрещено", texture: "012.jpg", function: "vehicleType != 'animal'" },
	{ name: "Движение автопоездов запрещено", texture: "013.jpg", function: "vehicleType != 'roadtrain'" },
	{ name: "Опасность (взрывоопасные вещества)", texture: "014.jpg" },
	{ name: "Движение с прицепом запрещено", texture: "015.jpg", function: "hasTrailer == false" },
	{ name: "Ограничение массы", texture: "016.jpg", function: "weight <= 8" },
	{ name: "Ограничение нагрузки на ось", texture: "017.jpg", function: "axleLoad <= 6" },
	{ name: "Ограничение высоты", texture: "018.jpg", function: "height <= 4" },
	{ name: "Ограничение ширины", texture: "019.jpg", function: "width <= 2.5" },
	{ name: "Ограничение длины", texture: "020.jpg", function: "length <= 12" },
	{ name: "Ограничение массы прицепа", texture: "021.jpg", function: "trailerWeight <= 3.5" },
	{ name: "Въезд запрещён (кирпич)", texture: "022.jpg" },
	{ name: "Поворот налево запрещён", texture: "023.jpg", function: "direction != 'left'" },
	{ name: "Поворот направо запрещён", texture: "024.jpg", function: "direction != 'right'" },
	{ name: "Разворот запрещён", texture: "025.jpg", function: "direction != 'u-turn'" },
	{ name: "Обгон запрещён", texture: "026.jpg", function: "isOvertaking == false" },
	{ name: "Обгон грузовикам запрещён", texture: "027.jpg", function: "!(isOvertaking && vehicleType == 'truck')" },
	{ name: "Движение грузовиков запрещено (дублируется)", texture: "028.jpg", function: "vehicleType != 'truck'" },
	{ name: "Конец зоны всех ограничений", texture: "029.jpg" },
	{ name: "Ограничение скорости 40", texture: "030.jpg", function: "speed <= 40", message: "Превышение скорости (40)" },
	{ name: "Ограничение скорости 50", texture: "031.jpg", function: "speed <= 50", message: "Превышение скорости (50)" },
	{ name: "Ограничение скорости 60", texture: "032.jpg", function: "speed <= 60", message: "Превышение скорости (60)" },
	{ name: "Ограничение скорости 70", texture: "033.jpg", function: "speed <= 70", message: "Превышение скорости (70)" },
	{ name: "Ограничение скорости 80", texture: "034.jpg", function: "speed <= 80", message: "Превышение скорости (80)" },
	{ name: "Ограничение скорости 90", texture: "035.jpg", function: "speed <= 90", message: "Превышение скорости (90)" },
	{ name: "Ограничение скорости 100", texture: "036.jpg", function: "speed <= 100", message: "Превышение скорости (100)" },
	{ name: "Ограничение скорости 110", texture: "037.jpg", function: "speed <= 110", message: "Превышение скорости (110)" },
	{ name: "Ограничение скорости 120", texture: "038.jpg", function: "speed <= 120", message: "Превышение скорости (120)" },
	{ name: "Ограничение скорости 130", texture: "039.jpg", function: "speed <= 130", message: "Превышение скорости (130)" },
	{ name: "Конец всех ограничений", texture: "040.jpg" },
	{ name: "Движение прямо", texture: "041.jpg", function: "direction == 'forward'" },
	{ name: "Движение направо", texture: "042.jpg", function: "direction == 'right'" },
	{ name: "Движение налево", texture: "043.jpg", function: "direction == 'left'" },
	{ name: "Движение прямо или направо", texture: "044.jpg", function: "direction == 'forward' || direction == 'right'" },
	{ name: "Движение прямо или налево", texture: "045.jpg", function: "direction == 'forward' || direction == 'left'" },
	{ name: "Движение направо или налево", texture: "046.jpg", function: "direction == 'left' || direction == 'right'" },
	{ name: "Поворот направо", texture: "047.jpg", function: "direction == 'right'" },
	{ name: "Поворот налево", texture: "048.jpg", function: "direction == 'left'" },
	{ name: "Объезд препятствия справа или слева", texture: "049.jpg" },
	{ name: "Кольцевое движение", texture: "050.jpg", function: "inRoundabout == true" },
	{ name: "Движение легковых автомобилей", texture: "051.jpg", function: "vehicleType == 'car'" },
	{ name: "Движение велосипедов", texture: "052.jpg", function: "vehicleType == 'bicycle'" },
	{ name: "Движение пешеходов", texture: "053.jpg", function: "vehicleType == 'pedestrian'" },
	{
		name: "Движение пешеходов и велосипедистов",
		texture: "054.jpg",
		function: "vehicleType == 'pedestrian' || vehicleType == 'bicycle'",
	},
	{ name: "Движение всадников", texture: "055.jpg", function: "vehicleType == 'horse'" },
	{ name: "Минимальная скорость 50", texture: "056.jpg", function: "speed >= 50" },
	{ name: "Конец минимальной скорости 50", texture: "057.jpg" },
]